version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: medods-mongo
    restart: always
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d/init-mongo:ro
      - ./mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=medods
      - MONGO_INITDB_ROOT_USERNAME=medods
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017-27019:27017-27019"
